// Copied from Eternal Terminal (https://github.com/MisterTea/EternalTerminal),
// proto/ET.proto at commit 6f53869473a16407b59f1f3382d291ab97b4f64f.
// Copyright Jason Gauci and contributors, licensed under the Apache License,
// Version 2.0. Unmodified apart from this header; see NOTICE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ET.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EtPacketType int32

const (
	// Count down from 254 to avoid collisions
	EtPacketType_HEARTBEAT        EtPacketType = 254
	EtPacketType_INITIAL_PAYLOAD  EtPacketType = 253
	EtPacketType_INITIAL_RESPONSE EtPacketType = 252
)

// Enum value maps for EtPacketType.
var (
	EtPacketType_name = map[int32]string{
		254: "HEARTBEAT",
		253: "INITIAL_PAYLOAD",
		252: "INITIAL_RESPONSE",
	}
	EtPacketType_value = map[string]int32{
		"HEARTBEAT":        254,
		"INITIAL_PAYLOAD":  253,
		"INITIAL_RESPONSE": 252,
	}
)

func (x EtPacketType) Enum() *EtPacketType {
	p := new(EtPacketType)
	*p = x
	return p
}

func (x EtPacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EtPacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_ET_proto_enumTypes[0].Descriptor()
}

func (EtPacketType) Type() protoreflect.EnumType {
	return &file_ET_proto_enumTypes[0]
}

func (x EtPacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ConnectStatus int32

const (
	ConnectStatus_NEW_CLIENT          ConnectStatus = 1
	ConnectStatus_RETURNING_CLIENT    ConnectStatus = 2
	ConnectStatus_INVALID_KEY         ConnectStatus = 3
	ConnectStatus_MISMATCHED_PROTOCOL ConnectStatus = 4
)

// Enum value maps for ConnectStatus.
var (
	ConnectStatus_name = map[int32]string{
		1: "NEW_CLIENT",
		2: "RETURNING_CLIENT",
		3: "INVALID_KEY",
		4: "MISMATCHED_PROTOCOL",
	}
	ConnectStatus_value = map[string]int32{
		"NEW_CLIENT":          1,
		"RETURNING_CLIENT":    2,
		"INVALID_KEY":         3,
		"MISMATCHED_PROTOCOL": 4,
	}
)

func (x ConnectStatus) Enum() *ConnectStatus {
	p := new(ConnectStatus)
	*p = x
	return p
}

func (x ConnectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ET_proto_enumTypes[1].Descriptor()
}

func (ConnectStatus) Type() protoreflect.EnumType {
	return &file_ET_proto_enumTypes[1]
}

func (x ConnectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ConnectRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClientId    *string                `protobuf:"bytes,1,opt,name=clientId"`
	xxx_hidden_Version     int32                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_ET_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ET_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectRequest) GetClientId() string {
	if x != nil {
		if x.xxx_hidden_ClientId != nil {
			return *x.xxx_hidden_ClientId
		}
		return ""
	}
	return ""
}

func (x *ConnectRequest) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *ConnectRequest) SetClientId(v string) {
	x.xxx_hidden_ClientId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConnectRequest) SetVersion(v int32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ConnectRequest) HasClientId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConnectRequest) ClearClientId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ClientId = nil
}

func (x *ConnectRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type ConnectRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ClientId *string
	Version  *int32
}

func (b0 ConnectRequest_builder) Build() *ConnectRequest {
	m0 := &ConnectRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ClientId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ClientId = b.ClientId
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type ConnectResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      ConnectStatus          `protobuf:"varint,1,opt,name=status,enum=et.ConnectStatus"`
	xxx_hidden_Error       *string                `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_ET_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ET_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConnectResponse) GetStatus() ConnectStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Status
		}
	}
	return ConnectStatus_NEW_CLIENT
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *ConnectResponse) SetStatus(v ConnectStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConnectResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ConnectResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConnectResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConnectResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = ConnectStatus_NEW_CLIENT
}

func (x *ConnectResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Error = nil
}

type ConnectResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status *ConnectStatus
	Error  *string
}

func (b0 ConnectResponse_builder) Build() *ConnectResponse {
	m0 := &ConnectResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = *b.Status
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type SequenceHeader struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SequenceNumber int32                  `protobuf:"varint,1,opt,name=sequenceNumber"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SequenceHeader) Reset() {
	*x = SequenceHeader{}
	mi := &file_ET_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceHeader) ProtoMessage() {}

func (x *SequenceHeader) ProtoReflect() protoreflect.Message {
	mi := &file_ET_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SequenceHeader) GetSequenceNumber() int32 {
	if x != nil {
		return x.xxx_hidden_SequenceNumber
	}
	return 0
}

func (x *SequenceHeader) SetSequenceNumber(v int32) {
	x.xxx_hidden_SequenceNumber = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SequenceHeader) HasSequenceNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SequenceHeader) ClearSequenceNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SequenceNumber = 0
}

type SequenceHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SequenceNumber *int32
}

func (b0 SequenceHeader_builder) Build() *SequenceHeader {
	m0 := &SequenceHeader{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SequenceNumber != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_SequenceNumber = *b.SequenceNumber
	}
	return m0
}

type CatchupBuffer struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Buffer [][]byte               `protobuf:"bytes,1,rep,name=buffer"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CatchupBuffer) Reset() {
	*x = CatchupBuffer{}
	mi := &file_ET_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatchupBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatchupBuffer) ProtoMessage() {}

func (x *CatchupBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_ET_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatchupBuffer) GetBuffer() [][]byte {
	if x != nil {
		return x.xxx_hidden_Buffer
	}
	return nil
}

func (x *CatchupBuffer) SetBuffer(v [][]byte) {
	x.xxx_hidden_Buffer = v
}

type CatchupBuffer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Buffer [][]byte
}

func (b0 CatchupBuffer_builder) Build() *CatchupBuffer {
	m0 := &CatchupBuffer{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Buffer = b.Buffer
	return m0
}

type SocketEndpoint struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Port        int32                  `protobuf:"varint,2,opt,name=port"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SocketEndpoint) Reset() {
	*x = SocketEndpoint{}
	mi := &file_ET_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocketEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketEndpoint) ProtoMessage() {}

func (x *SocketEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_ET_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SocketEndpoint) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *SocketEndpoint) GetPort() int32 {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return 0
}

func (x *SocketEndpoint) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SocketEndpoint) SetPort(v int32) {
	x.xxx_hidden_Port = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SocketEndpoint) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SocketEndpoint) HasPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SocketEndpoint) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *SocketEndpoint) ClearPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Port = 0
}

type SocketEndpoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
	Port *int32
}

func (b0 SocketEndpoint_builder) Build() *SocketEndpoint {
	m0 := &SocketEndpoint{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Name = b.Name
	}
	if b.Port != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Port = *b.Port
	}
	return m0
}

var File_ET_proto protoreflect.FileDescriptor

const file_ET_proto_rawDesc = "" +
	"\n" +
	"\bET.proto\x12\x02et\"F\n" +
	"\x0eConnectRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"R\n" +
	"\x0fConnectResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.et.ConnectStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x0eSequenceHeader\x12&\n" +
	"\x0esequenceNumber\x18\x01 \x01(\x05R\x0esequenceNumber\"'\n" +
	"\rCatchupBuffer\x12\x16\n" +
	"\x06buffer\x18\x01 \x03(\fR\x06buffer\"8\n" +
	"\x0eSocketEndpoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port*K\n" +
	"\fEtPacketType\x12\x0e\n" +
	"\tHEARTBEAT\x10\xfe\x01\x12\x14\n" +
	"\x0fINITIAL_PAYLOAD\x10\xfd\x01\x12\x15\n" +
	"\x10INITIAL_RESPONSE\x10\xfc\x01*_\n" +
	"\rConnectStatus\x12\x0e\n" +
	"\n" +
	"NEW_CLIENT\x10\x01\x12\x14\n" +
	"\x10RETURNING_CLIENT\x10\x02\x12\x0f\n" +
	"\vINVALID_KEY\x10\x03\x12\x17\n" +
	"\x13MISMATCHED_PROTOCOL\x10\x04B\x02H\x03"

var file_ET_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ET_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ET_proto_goTypes = []any{
	(EtPacketType)(0),       // 0: et.EtPacketType
	(ConnectStatus)(0),      // 1: et.ConnectStatus
	(*ConnectRequest)(nil),  // 2: et.ConnectRequest
	(*ConnectResponse)(nil), // 3: et.ConnectResponse
	(*SequenceHeader)(nil),  // 4: et.SequenceHeader
	(*CatchupBuffer)(nil),   // 5: et.CatchupBuffer
	(*SocketEndpoint)(nil),  // 6: et.SocketEndpoint
}
var file_ET_proto_depIdxs = []int32{
	1, // 0: et.ConnectResponse.status:type_name -> et.ConnectStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ET_proto_init() }
func file_ET_proto_init() {
	if File_ET_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ET_proto_rawDesc), len(file_ET_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ET_proto_goTypes,
		DependencyIndexes: file_ET_proto_depIdxs,
		EnumInfos:         file_ET_proto_enumTypes,
		MessageInfos:      file_ET_proto_msgTypes,
	}.Build()
	File_ET_proto = out.File
	file_ET_proto_goTypes = nil
	file_ET_proto_depIdxs = nil
}
