// Copied from Eternal Terminal (https://github.com/MisterTea/EternalTerminal),
// proto/ETerminal.proto at commit 6f53869473a16407b59f1f3382d291ab97b4f64f.
// Copyright Jason Gauci and contributors, licensed under the Apache License,
// Version 2.0. Unmodified apart from this header; see NOTICE.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ETerminal.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TerminalPacketType int32

const (
	TerminalPacketType_KEEP_ALIVE                        TerminalPacketType = 0
	TerminalPacketType_TERMINAL_BUFFER                   TerminalPacketType = 1
	TerminalPacketType_TERMINAL_INFO                     TerminalPacketType = 2
	TerminalPacketType_PORT_FORWARD_DESTINATION_REQUEST  TerminalPacketType = 5
	TerminalPacketType_PORT_FORWARD_DESTINATION_RESPONSE TerminalPacketType = 6
	TerminalPacketType_PORT_FORWARD_DATA                 TerminalPacketType = 7
	TerminalPacketType_TERMINAL_USER_INFO                TerminalPacketType = 8
	TerminalPacketType_TERMINAL_INIT                     TerminalPacketType = 9
	TerminalPacketType_JUMPHOST_INIT                     TerminalPacketType = 10
	TerminalPacketType_TERMINAL_CLOSE                    TerminalPacketType = 11
	// Wait status of the remote shell/command, sent once when the session ends.
	TerminalPacketType_TERMINAL_EXIT_STATUS TerminalPacketType = 12
)

// Enum value maps for TerminalPacketType.
var (
	TerminalPacketType_name = map[int32]string{
		0:  "KEEP_ALIVE",
		1:  "TERMINAL_BUFFER",
		2:  "TERMINAL_INFO",
		5:  "PORT_FORWARD_DESTINATION_REQUEST",
		6:  "PORT_FORWARD_DESTINATION_RESPONSE",
		7:  "PORT_FORWARD_DATA",
		8:  "TERMINAL_USER_INFO",
		9:  "TERMINAL_INIT",
		10: "JUMPHOST_INIT",
		11: "TERMINAL_CLOSE",
		12: "TERMINAL_EXIT_STATUS",
	}
	TerminalPacketType_value = map[string]int32{
		"KEEP_ALIVE":                        0,
		"TERMINAL_BUFFER":                   1,
		"TERMINAL_INFO":                     2,
		"PORT_FORWARD_DESTINATION_REQUEST":  5,
		"PORT_FORWARD_DESTINATION_RESPONSE": 6,
		"PORT_FORWARD_DATA":                 7,
		"TERMINAL_USER_INFO":                8,
		"TERMINAL_INIT":                     9,
		"JUMPHOST_INIT":                     10,
		"TERMINAL_CLOSE":                    11,
		"TERMINAL_EXIT_STATUS":              12,
	}
)

func (x TerminalPacketType) Enum() *TerminalPacketType {
	p := new(TerminalPacketType)
	*p = x
	return p
}

func (x TerminalPacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalPacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_ETerminal_proto_enumTypes[0].Descriptor()
}

func (TerminalPacketType) Type() protoreflect.EnumType {
	return &file_ETerminal_proto_enumTypes[0]
}

func (x TerminalPacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TerminalBuffer struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Buffer      []byte                 `protobuf:"bytes,1,opt,name=buffer"`
	xxx_hidden_IsStderr    bool                   `protobuf:"varint,2,opt,name=is_stderr,json=isStderr,def=0"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

// Default values for TerminalBuffer fields.
const (
	Default_TerminalBuffer_IsStderr = bool(false)
)

func (x *TerminalBuffer) Reset() {
	*x = TerminalBuffer{}
	mi := &file_ETerminal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalBuffer) ProtoMessage() {}

func (x *TerminalBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TerminalBuffer) GetBuffer() []byte {
	if x != nil {
		return x.xxx_hidden_Buffer
	}
	return nil
}

func (x *TerminalBuffer) GetIsStderr() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_IsStderr
		}
	}
	return Default_TerminalBuffer_IsStderr
}

func (x *TerminalBuffer) SetBuffer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Buffer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *TerminalBuffer) SetIsStderr(v bool) {
	x.xxx_hidden_IsStderr = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *TerminalBuffer) HasBuffer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TerminalBuffer) HasIsStderr() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TerminalBuffer) ClearBuffer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Buffer = nil
}

func (x *TerminalBuffer) ClearIsStderr() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
}

type TerminalBuffer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Buffer []byte
	// When true, buffer is remote stderr (raw pipe / -T sessions only).
	// Named is_stderr (not stderr): musl #defines stderr as a macro.
	IsStderr *bool
}

func (b0 TerminalBuffer_builder) Build() *TerminalBuffer {
	m0 := &TerminalBuffer{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Buffer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Buffer = b.Buffer
	}
	if b.IsStderr != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_IsStderr = *b.IsStderr
	}
	return m0
}

// Process status for the remote terminal child (OpenSSH-style exit code).
type TerminalExitStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Exitcode    int32                  `protobuf:"varint,1,opt,name=exitcode"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TerminalExitStatus) Reset() {
	*x = TerminalExitStatus{}
	mi := &file_ETerminal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalExitStatus) ProtoMessage() {}

func (x *TerminalExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TerminalExitStatus) GetExitcode() int32 {
	if x != nil {
		return x.xxx_hidden_Exitcode
	}
	return 0
}

func (x *TerminalExitStatus) SetExitcode(v int32) {
	x.xxx_hidden_Exitcode = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TerminalExitStatus) HasExitcode() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TerminalExitStatus) ClearExitcode() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Exitcode = 0
}

type TerminalExitStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Normalized status: WEXITSTATUS when exited, or 128+signal when signaled.
	Exitcode *int32
}

func (b0 TerminalExitStatus_builder) Build() *TerminalExitStatus {
	m0 := &TerminalExitStatus{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Exitcode != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Exitcode = *b.Exitcode
	}
	return m0
}

type TerminalInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Row         int32                  `protobuf:"varint,2,opt,name=row"`
	xxx_hidden_Column      int32                  `protobuf:"varint,3,opt,name=column"`
	xxx_hidden_Width       int32                  `protobuf:"varint,4,opt,name=width"`
	xxx_hidden_Height      int32                  `protobuf:"varint,5,opt,name=height"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TerminalInfo) Reset() {
	*x = TerminalInfo{}
	mi := &file_ETerminal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInfo) ProtoMessage() {}

func (x *TerminalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TerminalInfo) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *TerminalInfo) GetRow() int32 {
	if x != nil {
		return x.xxx_hidden_Row
	}
	return 0
}

func (x *TerminalInfo) GetColumn() int32 {
	if x != nil {
		return x.xxx_hidden_Column
	}
	return 0
}

func (x *TerminalInfo) GetWidth() int32 {
	if x != nil {
		return x.xxx_hidden_Width
	}
	return 0
}

func (x *TerminalInfo) GetHeight() int32 {
	if x != nil {
		return x.xxx_hidden_Height
	}
	return 0
}

func (x *TerminalInfo) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *TerminalInfo) SetRow(v int32) {
	x.xxx_hidden_Row = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *TerminalInfo) SetColumn(v int32) {
	x.xxx_hidden_Column = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *TerminalInfo) SetWidth(v int32) {
	x.xxx_hidden_Width = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *TerminalInfo) SetHeight(v int32) {
	x.xxx_hidden_Height = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *TerminalInfo) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TerminalInfo) HasRow() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TerminalInfo) HasColumn() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TerminalInfo) HasWidth() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TerminalInfo) HasHeight() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TerminalInfo) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *TerminalInfo) ClearRow() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Row = 0
}

func (x *TerminalInfo) ClearColumn() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Column = 0
}

func (x *TerminalInfo) ClearWidth() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Width = 0
}

func (x *TerminalInfo) ClearHeight() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Height = 0
}

type TerminalInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     *string
	Row    *int32
	Column *int32
	Width  *int32
	Height *int32
}

func (b0 TerminalInfo_builder) Build() *TerminalInfo {
	m0 := &TerminalInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Row != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Row = *b.Row
	}
	if b.Column != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Column = *b.Column
	}
	if b.Width != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Width = *b.Width
	}
	if b.Height != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Height = *b.Height
	}
	return m0
}

type PortForwardSourceRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Source              *SocketEndpoint        `protobuf:"bytes,1,opt,name=source"`
	xxx_hidden_Destination         *SocketEndpoint        `protobuf:"bytes,2,opt,name=destination"`
	xxx_hidden_Environmentvariable *string                `protobuf:"bytes,3,opt,name=environmentvariable"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *PortForwardSourceRequest) Reset() {
	*x = PortForwardSourceRequest{}
	mi := &file_ETerminal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSourceRequest) ProtoMessage() {}

func (x *PortForwardSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortForwardSourceRequest) GetSource() *SocketEndpoint {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *PortForwardSourceRequest) GetDestination() *SocketEndpoint {
	if x != nil {
		return x.xxx_hidden_Destination
	}
	return nil
}

func (x *PortForwardSourceRequest) GetEnvironmentvariable() string {
	if x != nil {
		if x.xxx_hidden_Environmentvariable != nil {
			return *x.xxx_hidden_Environmentvariable
		}
		return ""
	}
	return ""
}

func (x *PortForwardSourceRequest) SetSource(v *SocketEndpoint) {
	x.xxx_hidden_Source = v
}

func (x *PortForwardSourceRequest) SetDestination(v *SocketEndpoint) {
	x.xxx_hidden_Destination = v
}

func (x *PortForwardSourceRequest) SetEnvironmentvariable(v string) {
	x.xxx_hidden_Environmentvariable = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *PortForwardSourceRequest) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *PortForwardSourceRequest) HasDestination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Destination != nil
}

func (x *PortForwardSourceRequest) HasEnvironmentvariable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PortForwardSourceRequest) ClearSource() {
	x.xxx_hidden_Source = nil
}

func (x *PortForwardSourceRequest) ClearDestination() {
	x.xxx_hidden_Destination = nil
}

func (x *PortForwardSourceRequest) ClearEnvironmentvariable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Environmentvariable = nil
}

type PortForwardSourceRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Source              *SocketEndpoint
	Destination         *SocketEndpoint
	Environmentvariable *string
}

func (b0 PortForwardSourceRequest_builder) Build() *PortForwardSourceRequest {
	m0 := &PortForwardSourceRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_Destination = b.Destination
	if b.Environmentvariable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Environmentvariable = b.Environmentvariable
	}
	return m0
}

type PortForwardSourceResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Error       *string                `protobuf:"bytes,1,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PortForwardSourceResponse) Reset() {
	*x = PortForwardSourceResponse{}
	mi := &file_ETerminal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardSourceResponse) ProtoMessage() {}

func (x *PortForwardSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortForwardSourceResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *PortForwardSourceResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *PortForwardSourceResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PortForwardSourceResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Error = nil
}

type PortForwardSourceResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Error *string
}

func (b0 PortForwardSourceResponse_builder) Build() *PortForwardSourceResponse {
	m0 := &PortForwardSourceResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type PortForwardDestinationRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Destination *SocketEndpoint        `protobuf:"bytes,1,opt,name=destination"`
	xxx_hidden_Fd          int32                  `protobuf:"varint,2,opt,name=fd"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PortForwardDestinationRequest) Reset() {
	*x = PortForwardDestinationRequest{}
	mi := &file_ETerminal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardDestinationRequest) ProtoMessage() {}

func (x *PortForwardDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortForwardDestinationRequest) GetDestination() *SocketEndpoint {
	if x != nil {
		return x.xxx_hidden_Destination
	}
	return nil
}

func (x *PortForwardDestinationRequest) GetFd() int32 {
	if x != nil {
		return x.xxx_hidden_Fd
	}
	return 0
}

func (x *PortForwardDestinationRequest) SetDestination(v *SocketEndpoint) {
	x.xxx_hidden_Destination = v
}

func (x *PortForwardDestinationRequest) SetFd(v int32) {
	x.xxx_hidden_Fd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *PortForwardDestinationRequest) HasDestination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Destination != nil
}

func (x *PortForwardDestinationRequest) HasFd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PortForwardDestinationRequest) ClearDestination() {
	x.xxx_hidden_Destination = nil
}

func (x *PortForwardDestinationRequest) ClearFd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Fd = 0
}

type PortForwardDestinationRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Destination *SocketEndpoint
	Fd          *int32
}

func (b0 PortForwardDestinationRequest_builder) Build() *PortForwardDestinationRequest {
	m0 := &PortForwardDestinationRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Destination = b.Destination
	if b.Fd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Fd = *b.Fd
	}
	return m0
}

type PortForwardDestinationResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Clientfd    int32                  `protobuf:"varint,1,opt,name=clientfd"`
	xxx_hidden_Socketid    int32                  `protobuf:"varint,2,opt,name=socketid"`
	xxx_hidden_Error       *string                `protobuf:"bytes,3,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PortForwardDestinationResponse) Reset() {
	*x = PortForwardDestinationResponse{}
	mi := &file_ETerminal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardDestinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardDestinationResponse) ProtoMessage() {}

func (x *PortForwardDestinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortForwardDestinationResponse) GetClientfd() int32 {
	if x != nil {
		return x.xxx_hidden_Clientfd
	}
	return 0
}

func (x *PortForwardDestinationResponse) GetSocketid() int32 {
	if x != nil {
		return x.xxx_hidden_Socketid
	}
	return 0
}

func (x *PortForwardDestinationResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *PortForwardDestinationResponse) SetClientfd(v int32) {
	x.xxx_hidden_Clientfd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *PortForwardDestinationResponse) SetSocketid(v int32) {
	x.xxx_hidden_Socketid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *PortForwardDestinationResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *PortForwardDestinationResponse) HasClientfd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PortForwardDestinationResponse) HasSocketid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PortForwardDestinationResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PortForwardDestinationResponse) ClearClientfd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Clientfd = 0
}

func (x *PortForwardDestinationResponse) ClearSocketid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Socketid = 0
}

func (x *PortForwardDestinationResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Error = nil
}

type PortForwardDestinationResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Clientfd *int32
	Socketid *int32
	Error    *string
}

func (b0 PortForwardDestinationResponse_builder) Build() *PortForwardDestinationResponse {
	m0 := &PortForwardDestinationResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Clientfd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Clientfd = *b.Clientfd
	}
	if b.Socketid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Socketid = *b.Socketid
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type PortForwardData struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sourcetodestination bool                   `protobuf:"varint,1,opt,name=sourcetodestination"`
	xxx_hidden_Socketid            int32                  `protobuf:"varint,2,opt,name=socketid"`
	xxx_hidden_Buffer              []byte                 `protobuf:"bytes,3,opt,name=buffer"`
	xxx_hidden_Error               *string                `protobuf:"bytes,4,opt,name=error"`
	xxx_hidden_Closed              bool                   `protobuf:"varint,5,opt,name=closed"`
	xxx_hidden_HalfClose           bool                   `protobuf:"varint,6,opt,name=half_close,json=halfClose"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *PortForwardData) Reset() {
	*x = PortForwardData{}
	mi := &file_ETerminal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardData) ProtoMessage() {}

func (x *PortForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortForwardData) GetSourcetodestination() bool {
	if x != nil {
		return x.xxx_hidden_Sourcetodestination
	}
	return false
}

func (x *PortForwardData) GetSocketid() int32 {
	if x != nil {
		return x.xxx_hidden_Socketid
	}
	return 0
}

func (x *PortForwardData) GetBuffer() []byte {
	if x != nil {
		return x.xxx_hidden_Buffer
	}
	return nil
}

func (x *PortForwardData) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *PortForwardData) GetClosed() bool {
	if x != nil {
		return x.xxx_hidden_Closed
	}
	return false
}

func (x *PortForwardData) GetHalfClose() bool {
	if x != nil {
		return x.xxx_hidden_HalfClose
	}
	return false
}

func (x *PortForwardData) SetSourcetodestination(v bool) {
	x.xxx_hidden_Sourcetodestination = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *PortForwardData) SetSocketid(v int32) {
	x.xxx_hidden_Socketid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *PortForwardData) SetBuffer(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Buffer = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *PortForwardData) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *PortForwardData) SetClosed(v bool) {
	x.xxx_hidden_Closed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *PortForwardData) SetHalfClose(v bool) {
	x.xxx_hidden_HalfClose = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *PortForwardData) HasSourcetodestination() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PortForwardData) HasSocketid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PortForwardData) HasBuffer() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *PortForwardData) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *PortForwardData) HasClosed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *PortForwardData) HasHalfClose() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *PortForwardData) ClearSourcetodestination() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Sourcetodestination = false
}

func (x *PortForwardData) ClearSocketid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Socketid = 0
}

func (x *PortForwardData) ClearBuffer() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Buffer = nil
}

func (x *PortForwardData) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Error = nil
}

func (x *PortForwardData) ClearClosed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Closed = false
}

func (x *PortForwardData) ClearHalfClose() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_HalfClose = false
}

type PortForwardData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sourcetodestination *bool
	Socketid            *int32
	Buffer              []byte
	Error               *string
	Closed              *bool
	// Source finished writing. Keep the destination open for the reply direction.
	HalfClose *bool
}

func (b0 PortForwardData_builder) Build() *PortForwardData {
	m0 := &PortForwardData{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Sourcetodestination != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Sourcetodestination = *b.Sourcetodestination
	}
	if b.Socketid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Socketid = *b.Socketid
	}
	if b.Buffer != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Buffer = b.Buffer
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Error = b.Error
	}
	if b.Closed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Closed = *b.Closed
	}
	if b.HalfClose != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_HalfClose = *b.HalfClose
	}
	return m0
}

type InitialPayload struct {
	state                           protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Jumphost             bool                         `protobuf:"varint,1,opt,name=jumphost,def=0"`
	xxx_hidden_Reversetunnels       *[]*PortForwardSourceRequest `protobuf:"bytes,2,rep,name=reversetunnels"`
	xxx_hidden_Environmentvariables map[string]string            `protobuf:"bytes,3,rep,name=environmentvariables" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_NoPty                bool                         `protobuf:"varint,4,opt,name=no_pty,json=noPty,def=0"`
	xxx_hidden_Command              *string                      `protobuf:"bytes,5,opt,name=command"`
	xxx_hidden_SupportsExitStatus   bool                         `protobuf:"varint,6,opt,name=supports_exit_status,json=supportsExitStatus,def=0"`
	xxx_hidden_NoShell              bool                         `protobuf:"varint,7,opt,name=no_shell,json=noShell,def=0"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

// Default values for InitialPayload fields.
const (
	Default_InitialPayload_Jumphost           = bool(false)
	Default_InitialPayload_NoPty              = bool(false)
	Default_InitialPayload_SupportsExitStatus = bool(false)
	Default_InitialPayload_NoShell            = bool(false)
)

func (x *InitialPayload) Reset() {
	*x = InitialPayload{}
	mi := &file_ETerminal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialPayload) ProtoMessage() {}

func (x *InitialPayload) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitialPayload) GetJumphost() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Jumphost
		}
	}
	return Default_InitialPayload_Jumphost
}

func (x *InitialPayload) GetReversetunnels() []*PortForwardSourceRequest {
	if x != nil {
		if x.xxx_hidden_Reversetunnels != nil {
			return *x.xxx_hidden_Reversetunnels
		}
	}
	return nil
}

func (x *InitialPayload) GetEnvironmentvariables() map[string]string {
	if x != nil {
		return x.xxx_hidden_Environmentvariables
	}
	return nil
}

func (x *InitialPayload) GetNoPty() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_NoPty
		}
	}
	return Default_InitialPayload_NoPty
}

func (x *InitialPayload) GetCommand() string {
	if x != nil {
		if x.xxx_hidden_Command != nil {
			return *x.xxx_hidden_Command
		}
		return ""
	}
	return ""
}

func (x *InitialPayload) GetSupportsExitStatus() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_SupportsExitStatus
		}
	}
	return Default_InitialPayload_SupportsExitStatus
}

func (x *InitialPayload) GetNoShell() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 6) {
			return x.xxx_hidden_NoShell
		}
	}
	return Default_InitialPayload_NoShell
}

func (x *InitialPayload) SetJumphost(v bool) {
	x.xxx_hidden_Jumphost = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *InitialPayload) SetReversetunnels(v []*PortForwardSourceRequest) {
	x.xxx_hidden_Reversetunnels = &v
}

func (x *InitialPayload) SetEnvironmentvariables(v map[string]string) {
	x.xxx_hidden_Environmentvariables = v
}

func (x *InitialPayload) SetNoPty(v bool) {
	x.xxx_hidden_NoPty = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *InitialPayload) SetCommand(v string) {
	x.xxx_hidden_Command = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *InitialPayload) SetSupportsExitStatus(v bool) {
	x.xxx_hidden_SupportsExitStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *InitialPayload) SetNoShell(v bool) {
	x.xxx_hidden_NoShell = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *InitialPayload) HasJumphost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InitialPayload) HasNoPty() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *InitialPayload) HasCommand() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *InitialPayload) HasSupportsExitStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *InitialPayload) HasNoShell() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *InitialPayload) ClearJumphost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
}

func (x *InitialPayload) ClearNoPty() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
}

func (x *InitialPayload) ClearCommand() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Command = nil
}

func (x *InitialPayload) ClearSupportsExitStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
}

func (x *InitialPayload) ClearNoShell() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
}

type InitialPayload_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Jumphost             *bool
	Reversetunnels       []*PortForwardSourceRequest
	Environmentvariables map[string]string
	// When true, etterminal runs `command` on pipes instead of a login pty.
	NoPty   *bool
	Command *string
	// Set by clients that understand TERMINAL_EXIT_STATUS. Older clients leave
	// this unset, and etserver must not forward that packet to them.
	SupportsExitStatus *bool
	// ssh -W: keep the session without a pty or a shell.
	NoShell *bool
}

func (b0 InitialPayload_builder) Build() *InitialPayload {
	m0 := &InitialPayload{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Jumphost != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Jumphost = *b.Jumphost
	}
	x.xxx_hidden_Reversetunnels = &b.Reversetunnels
	x.xxx_hidden_Environmentvariables = b.Environmentvariables
	if b.NoPty != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_NoPty = *b.NoPty
	}
	if b.Command != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Command = b.Command
	}
	if b.SupportsExitStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_SupportsExitStatus = *b.SupportsExitStatus
	}
	if b.NoShell != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_NoShell = *b.NoShell
	}
	return m0
}

type InitialResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Error       *string                `protobuf:"bytes,1,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InitialResponse) Reset() {
	*x = InitialResponse{}
	mi := &file_ETerminal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialResponse) ProtoMessage() {}

func (x *InitialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitialResponse) GetError() string {
	if x != nil {
		if x.xxx_hidden_Error != nil {
			return *x.xxx_hidden_Error
		}
		return ""
	}
	return ""
}

func (x *InitialResponse) SetError(v string) {
	x.xxx_hidden_Error = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *InitialResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *InitialResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Error = nil
}

type InitialResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Error *string
}

func (b0 InitialResponse_builder) Build() *InitialResponse {
	m0 := &InitialResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

type ConfigParams struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Vlevel      int32                  `protobuf:"varint,1,opt,name=vlevel"`
	xxx_hidden_Minloglevel int32                  `protobuf:"varint,2,opt,name=minloglevel"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigParams) Reset() {
	*x = ConfigParams{}
	mi := &file_ETerminal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigParams) ProtoMessage() {}

func (x *ConfigParams) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigParams) GetVlevel() int32 {
	if x != nil {
		return x.xxx_hidden_Vlevel
	}
	return 0
}

func (x *ConfigParams) GetMinloglevel() int32 {
	if x != nil {
		return x.xxx_hidden_Minloglevel
	}
	return 0
}

func (x *ConfigParams) SetVlevel(v int32) {
	x.xxx_hidden_Vlevel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConfigParams) SetMinloglevel(v int32) {
	x.xxx_hidden_Minloglevel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ConfigParams) HasVlevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigParams) HasMinloglevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConfigParams) ClearVlevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Vlevel = 0
}

func (x *ConfigParams) ClearMinloglevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Minloglevel = 0
}

type ConfigParams_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Vlevel      *int32
	Minloglevel *int32
}

func (b0 ConfigParams_builder) Build() *ConfigParams {
	m0 := &ConfigParams{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Vlevel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Vlevel = *b.Vlevel
	}
	if b.Minloglevel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Minloglevel = *b.Minloglevel
	}
	return m0
}

type TermInit struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Environmentnames  []string               `protobuf:"bytes,1,rep,name=environmentnames"`
	xxx_hidden_Environmentvalues []string               `protobuf:"bytes,2,rep,name=environmentvalues"`
	xxx_hidden_NoPty             bool                   `protobuf:"varint,3,opt,name=no_pty,json=noPty,def=0"`
	xxx_hidden_Command           *string                `protobuf:"bytes,4,opt,name=command"`
	xxx_hidden_NoShell           bool                   `protobuf:"varint,5,opt,name=no_shell,json=noShell,def=0"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

// Default values for TermInit fields.
const (
	Default_TermInit_NoPty   = bool(false)
	Default_TermInit_NoShell = bool(false)
)

func (x *TermInit) Reset() {
	*x = TermInit{}
	mi := &file_ETerminal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermInit) ProtoMessage() {}

func (x *TermInit) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TermInit) GetEnvironmentnames() []string {
	if x != nil {
		return x.xxx_hidden_Environmentnames
	}
	return nil
}

func (x *TermInit) GetEnvironmentvalues() []string {
	if x != nil {
		return x.xxx_hidden_Environmentvalues
	}
	return nil
}

func (x *TermInit) GetNoPty() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_NoPty
		}
	}
	return Default_TermInit_NoPty
}

func (x *TermInit) GetCommand() string {
	if x != nil {
		if x.xxx_hidden_Command != nil {
			return *x.xxx_hidden_Command
		}
		return ""
	}
	return ""
}

func (x *TermInit) GetNoShell() bool {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 4) {
			return x.xxx_hidden_NoShell
		}
	}
	return Default_TermInit_NoShell
}

func (x *TermInit) SetEnvironmentnames(v []string) {
	x.xxx_hidden_Environmentnames = v
}

func (x *TermInit) SetEnvironmentvalues(v []string) {
	x.xxx_hidden_Environmentvalues = v
}

func (x *TermInit) SetNoPty(v bool) {
	x.xxx_hidden_NoPty = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *TermInit) SetCommand(v string) {
	x.xxx_hidden_Command = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *TermInit) SetNoShell(v bool) {
	x.xxx_hidden_NoShell = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *TermInit) HasNoPty() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TermInit) HasCommand() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TermInit) HasNoShell() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TermInit) ClearNoPty() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
}

func (x *TermInit) ClearCommand() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Command = nil
}

func (x *TermInit) ClearNoShell() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
}

type TermInit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Environmentnames  []string
	Environmentvalues []string
	NoPty             *bool
	Command           *string
	NoShell           *bool
}

func (b0 TermInit_builder) Build() *TermInit {
	m0 := &TermInit{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Environmentnames = b.Environmentnames
	x.xxx_hidden_Environmentvalues = b.Environmentvalues
	if b.NoPty != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_NoPty = *b.NoPty
	}
	if b.Command != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Command = b.Command
	}
	if b.NoShell != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_NoShell = *b.NoShell
	}
	return m0
}

type TerminalUserInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Passkey     *string                `protobuf:"bytes,2,opt,name=passkey"`
	xxx_hidden_Uid         int64                  `protobuf:"varint,3,opt,name=uid"`
	xxx_hidden_Gid         int64                  `protobuf:"varint,4,opt,name=gid"`
	xxx_hidden_Fd          int64                  `protobuf:"varint,5,opt,name=fd"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TerminalUserInfo) Reset() {
	*x = TerminalUserInfo{}
	mi := &file_ETerminal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalUserInfo) ProtoMessage() {}

func (x *TerminalUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ETerminal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TerminalUserInfo) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *TerminalUserInfo) GetPasskey() string {
	if x != nil {
		if x.xxx_hidden_Passkey != nil {
			return *x.xxx_hidden_Passkey
		}
		return ""
	}
	return ""
}

func (x *TerminalUserInfo) GetUid() int64 {
	if x != nil {
		return x.xxx_hidden_Uid
	}
	return 0
}

func (x *TerminalUserInfo) GetGid() int64 {
	if x != nil {
		return x.xxx_hidden_Gid
	}
	return 0
}

func (x *TerminalUserInfo) GetFd() int64 {
	if x != nil {
		return x.xxx_hidden_Fd
	}
	return 0
}

func (x *TerminalUserInfo) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *TerminalUserInfo) SetPasskey(v string) {
	x.xxx_hidden_Passkey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *TerminalUserInfo) SetUid(v int64) {
	x.xxx_hidden_Uid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *TerminalUserInfo) SetGid(v int64) {
	x.xxx_hidden_Gid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *TerminalUserInfo) SetFd(v int64) {
	x.xxx_hidden_Fd = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *TerminalUserInfo) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TerminalUserInfo) HasPasskey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TerminalUserInfo) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TerminalUserInfo) HasGid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TerminalUserInfo) HasFd() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TerminalUserInfo) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *TerminalUserInfo) ClearPasskey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Passkey = nil
}

func (x *TerminalUserInfo) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Uid = 0
}

func (x *TerminalUserInfo) ClearGid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Gid = 0
}

func (x *TerminalUserInfo) ClearFd() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Fd = 0
}

type TerminalUserInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Passkey *string
	Uid     *int64
	Gid     *int64
	Fd      *int64
}

func (b0 TerminalUserInfo_builder) Build() *TerminalUserInfo {
	m0 := &TerminalUserInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Id = b.Id
	}
	if b.Passkey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Passkey = b.Passkey
	}
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Uid = *b.Uid
	}
	if b.Gid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Gid = *b.Gid
	}
	if b.Fd != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Fd = *b.Fd
	}
	return m0
}

var File_ETerminal_proto protoreflect.FileDescriptor

const file_ETerminal_proto_rawDesc = "" +
	"\n" +
	"\x0fETerminal.proto\x12\x02et\x1a\bET.proto\"L\n" +
	"\x0eTerminalBuffer\x12\x16\n" +
	"\x06buffer\x18\x01 \x01(\fR\x06buffer\x12\"\n" +
	"\tis_stderr\x18\x02 \x01(\b:\x05falseR\bisStderr\"0\n" +
	"\x12TerminalExitStatus\x12\x1a\n" +
	"\bexitcode\x18\x01 \x01(\x05R\bexitcode\"v\n" +
	"\fTerminalInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\"\xae\x01\n" +
	"\x18PortForwardSourceRequest\x12*\n" +
	"\x06source\x18\x01 \x01(\v2\x12.et.SocketEndpointR\x06source\x124\n" +
	"\vdestination\x18\x02 \x01(\v2\x12.et.SocketEndpointR\vdestination\x120\n" +
	"\x13environmentvariable\x18\x03 \x01(\tR\x13environmentvariable\"1\n" +
	"\x19PortForwardSourceResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"e\n" +
	"\x1dPortForwardDestinationRequest\x124\n" +
	"\vdestination\x18\x01 \x01(\v2\x12.et.SocketEndpointR\vdestination\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x05R\x02fd\"n\n" +
	"\x1ePortForwardDestinationResponse\x12\x1a\n" +
	"\bclientfd\x18\x01 \x01(\x05R\bclientfd\x12\x1a\n" +
	"\bsocketid\x18\x02 \x01(\x05R\bsocketid\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xc4\x01\n" +
	"\x0fPortForwardData\x120\n" +
	"\x13sourcetodestination\x18\x01 \x01(\bR\x13sourcetodestination\x12\x1a\n" +
	"\bsocketid\x18\x02 \x01(\x05R\bsocketid\x12\x16\n" +
	"\x06buffer\x18\x03 \x01(\fR\x06buffer\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x16\n" +
	"\x06closed\x18\x05 \x01(\bR\x06closed\x12\x1d\n" +
	"\n" +
	"half_close\x18\x06 \x01(\bR\thalfClose\"\xb7\x03\n" +
	"\x0eInitialPayload\x12!\n" +
	"\bjumphost\x18\x01 \x01(\b:\x05falseR\bjumphost\x12D\n" +
	"\x0ereversetunnels\x18\x02 \x03(\v2\x1c.et.PortForwardSourceRequestR\x0ereversetunnels\x12`\n" +
	"\x14environmentvariables\x18\x03 \x03(\v2,.et.InitialPayload.EnvironmentvariablesEntryR\x14environmentvariables\x12\x1c\n" +
	"\x06no_pty\x18\x04 \x01(\b:\x05falseR\x05noPty\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x127\n" +
	"\x14supports_exit_status\x18\x06 \x01(\b:\x05falseR\x12supportsExitStatus\x12 \n" +
	"\bno_shell\x18\a \x01(\b:\x05falseR\anoShell\x1aG\n" +
	"\x19EnvironmentvariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\x0fInitialResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"H\n" +
	"\fConfigParams\x12\x16\n" +
	"\x06vlevel\x18\x01 \x01(\x05R\x06vlevel\x12 \n" +
	"\vminloglevel\x18\x02 \x01(\x05R\vminloglevel\"\xbe\x01\n" +
	"\bTermInit\x12*\n" +
	"\x10environmentnames\x18\x01 \x03(\tR\x10environmentnames\x12,\n" +
	"\x11environmentvalues\x18\x02 \x03(\tR\x11environmentvalues\x12\x1c\n" +
	"\x06no_pty\x18\x03 \x01(\b:\x05falseR\x05noPty\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12 \n" +
	"\bno_shell\x18\x05 \x01(\b:\x05falseR\anoShell\"p\n" +
	"\x10TerminalUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apasskey\x18\x02 \x01(\tR\apasskey\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x10\n" +
	"\x03gid\x18\x04 \x01(\x03R\x03gid\x12\x0e\n" +
	"\x02fd\x18\x05 \x01(\x03R\x02fd*\x9c\x02\n" +
	"\x12TerminalPacketType\x12\x0e\n" +
	"\n" +
	"KEEP_ALIVE\x10\x00\x12\x13\n" +
	"\x0fTERMINAL_BUFFER\x10\x01\x12\x11\n" +
	"\rTERMINAL_INFO\x10\x02\x12$\n" +
	" PORT_FORWARD_DESTINATION_REQUEST\x10\x05\x12%\n" +
	"!PORT_FORWARD_DESTINATION_RESPONSE\x10\x06\x12\x15\n" +
	"\x11PORT_FORWARD_DATA\x10\a\x12\x16\n" +
	"\x12TERMINAL_USER_INFO\x10\b\x12\x11\n" +
	"\rTERMINAL_INIT\x10\t\x12\x11\n" +
	"\rJUMPHOST_INIT\x10\n" +
	"\x12\x12\n" +
	"\x0eTERMINAL_CLOSE\x10\v\x12\x18\n" +
	"\x14TERMINAL_EXIT_STATUS\x10\fB\x02H\x03"

var file_ETerminal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ETerminal_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ETerminal_proto_goTypes = []any{
	(TerminalPacketType)(0),                // 0: et.TerminalPacketType
	(*TerminalBuffer)(nil),                 // 1: et.TerminalBuffer
	(*TerminalExitStatus)(nil),             // 2: et.TerminalExitStatus
	(*TerminalInfo)(nil),                   // 3: et.TerminalInfo
	(*PortForwardSourceRequest)(nil),       // 4: et.PortForwardSourceRequest
	(*PortForwardSourceResponse)(nil),      // 5: et.PortForwardSourceResponse
	(*PortForwardDestinationRequest)(nil),  // 6: et.PortForwardDestinationRequest
	(*PortForwardDestinationResponse)(nil), // 7: et.PortForwardDestinationResponse
	(*PortForwardData)(nil),                // 8: et.PortForwardData
	(*InitialPayload)(nil),                 // 9: et.InitialPayload
	(*InitialResponse)(nil),                // 10: et.InitialResponse
	(*ConfigParams)(nil),                   // 11: et.ConfigParams
	(*TermInit)(nil),                       // 12: et.TermInit
	(*TerminalUserInfo)(nil),               // 13: et.TerminalUserInfo
	nil,                                    // 14: et.InitialPayload.EnvironmentvariablesEntry
	(*SocketEndpoint)(nil),                 // 15: et.SocketEndpoint
}
var file_ETerminal_proto_depIdxs = []int32{
	15, // 0: et.PortForwardSourceRequest.source:type_name -> et.SocketEndpoint
	15, // 1: et.PortForwardSourceRequest.destination:type_name -> et.SocketEndpoint
	15, // 2: et.PortForwardDestinationRequest.destination:type_name -> et.SocketEndpoint
	4,  // 3: et.InitialPayload.reversetunnels:type_name -> et.PortForwardSourceRequest
	14, // 4: et.InitialPayload.environmentvariables:type_name -> et.InitialPayload.EnvironmentvariablesEntry
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ETerminal_proto_init() }
func file_ETerminal_proto_init() {
	if File_ETerminal_proto != nil {
		return
	}
	file_ET_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ETerminal_proto_rawDesc), len(file_ETerminal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ETerminal_proto_goTypes,
		DependencyIndexes: file_ETerminal_proto_depIdxs,
		EnumInfos:         file_ETerminal_proto_enumTypes,
		MessageInfos:      file_ETerminal_proto_msgTypes,
	}.Build()
	File_ETerminal_proto = out.File
	file_ETerminal_proto_goTypes = nil
	file_ETerminal_proto_depIdxs = nil
}
