// Code generated by "stringer -type=Header -trimprefix=Header"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeaderKeepAlive-0]
	_ = x[HeaderTerminalBuffer-1]
	_ = x[HeaderTerminalInfo-2]
	_ = x[HeaderTerminalClose-11]
	_ = x[HeaderTerminalExitStatus-12]
	_ = x[HeaderInitialResponse-252]
	_ = x[HeaderInitialPayload-253]
}

const (
	_Header_name_0 = "KeepAliveTerminalBufferTerminalInfo"
	_Header_name_1 = "TerminalCloseTerminalExitStatus"
	_Header_name_2 = "InitialResponseInitialPayload"
)

var (
	_Header_index_0 = [...]uint8{0, 9, 23, 35}
	_Header_index_1 = [...]uint8{0, 13, 31}
	_Header_index_2 = [...]uint8{0, 15, 29}
)

func (i Header) String() string {
	switch {
	case i <= 2:
		return _Header_name_0[_Header_index_0[i]:_Header_index_0[i+1]]
	case 11 <= i && i <= 12:
		i -= 11
		return _Header_name_1[_Header_index_1[i]:_Header_index_1[i+1]]
	case 252 <= i && i <= 253:
		i -= 252
		return _Header_name_2[_Header_index_2[i]:_Header_index_2[i+1]]
	default:
		return "Header(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
